version: '3.7'
services:
  library-db:
    image: postgres:11
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      MAX_CONNECTIONS: 300
    restart: always
    ports:
      - "5440:5432"
    command: [
        "postgres",
        "-c", "shared_preload_libraries=pg_stat_statements",
    ]