server.port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

logging:
  file.path: ./logs

