server.port: 8080

spring:
  liquibase:
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5440/library
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: farkar160@gmail.com
    password: pvveuotatfczimfj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  file.path: ./logs

